### ISSUE TITLE
[Feature request] Add option to switch to default Alt+Tab behavior

### ISSUE THREAD

**Issue by tnmma96** [gonzaarcr/unity-like-switcher-gnome-ext#1]
As the title says, I really hope that you could add an option to switch to default Alt+Tab behavior (first tab changes app), since some GNOME users (including me) have been accustomed to it.

Thank you in advance.

**Comment by gonzaarcr** [comment]
I added the setting on b823302. I’m gonna test it a little more and upload in a few days to the page.

**Comment by tnmma96** [comment]
@gonzaarcr May I ask if you have uploaded the new version to extensions.gnome.org? It's been a while.

**Comment by gonzaarcr** [comment]
Sorry, I completely forgot it. I just uploaded it, it will be in a couple of days.

**Comment by tnmma96** [comment]
@gonzaarcr I've just updated to the new version, so far it's been working well.
Thank you very much for your effort 👍
