### ISSUE TITLE
Feature request : Option to disable the colouring in the switcher 

### ISSUE THREAD

**Issue by ghost** [gonzaarcr/unity-like-switcher-gnome-ext#2]
I do like this extension a lot . Can you please add an option o disable the colored effects ? Maybe make it look like regular vanilla gnome app switcher . I like the extension's functionality to switch between open windows of the same app .

**Comment by gonzaarcr** [comment]
What this extension does is the colouring, what you are describing is vanilla gnome. If you want it to be default, go to Settings → Keybindings → Navigation and change the behaviour of switch between apps/windows.
